# Generated by Django 6.0.7 on 2026-07-22 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_average_rating_course_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningpath',
            old_name='is_publised',
            new_name='is_published',
        ),
    ]
